library(lmerTest);library (car); library (mlogit);library(lme4);library(nlme);library(psych);library(Matrix);library(lattice);library (memisc);library(ggplot2);library(lmtest);library(gvlma); library(Rfit); library(sm)

setwd("C:/Users/Kayla/OneDrive/projects/Political Language/Thesis/")

data = read.csv("thesis_data.csv", header=T, stringsAsFactor=F)
data = cbind(data, PA = rep(0, nrow(data)))
data$PA = ifelse(data$Party=="R", 0, 1)

data$Date = as.Date(data$Date, "%m/%d/%Y")
data$date = as.numeric(data$Date)

iraq = subset(data, Region=="Iraq")
iran = subset(data, Region=="Iran")
northkorea = subset(data, Region=="North Korea")
ink = subset(data, Region=="Iran"|Region=="North Korea")

iraqmat=as.matrix(iraq$date, iraq$YrsInCongress)
inkmat=as.matrix(ink$date, ink$YrsInCongress)
iraqD=subset(iraq, PA==1)
iraqR=subset(iraq, PA==0)
inkD=subset(ink, PA==1)
inkR=subset(ink, PA==0)

###Honesty
hm <- hcv(iraq$date, iraq$Honesty, display="lines")
sm.regression(y = iraq$Honesty, x = iraq$date, h = 185)
h<-as.data.frame(locator(n=10, type="l"))
hDate<-as.Date(h$x)
h<-cbind(h, hDate)
sm.regression(y = iraq$Honesty, x = iraq$date, h = 185, col.points="white")
sm.regression(y = iraq$Honesty, x = iraqmat, h = 185)
sm.regression(y = iraqD$Honesty, x = iraqD$date, h = 185, display="line")
sm.regression(y = iraqD$Honesty, x = iraqD$date, h = 185, lty=1, col.points="grey", xlab="Date", ylab="Honesty", axis(side=1, labels=ax, at=bx, las=2))
hd<-as.data.frame(locator(n=10, type="l"))
hdDate<-as.Date(hd$x)
hd<-cbind(hd, hdDate)
sm.regression(y = iraqR$Honesty, x = iraqR$date, h = 185, add=T, lty=3)
hr<-as.data.frame(locator(n=10, type="l"))
hrDate<-as.Date(hr$x)
hr<-cbind(hr, hrDate)

hm <- hcv(ink$date, ink$Honesty, display="none")
sm.regression(y = ink$Honesty, x = ink$date, h = 198)
h2<-as.data.frame(locator(n=10, type="l"))
h2Date<-as.Date(h2$x)
h2<-cbind(h2, h2Date)
sm.regression(ink$Honesty~ink$date, h = 198, col.points="white")
sm.regression(y = ink$Honesty, x = inkmat, h = 198)
sm.regression(y = inkD$Honesty, x = inkD$date, h = 198)
h2d<-as.data.frame(locator(n=10, type="l"))
h2dDate<-as.Date(h2d$x)
h2d<-cbind(h2d, h2dDate)
sm.regression(y = inkR$Honesty, x = inkR$date, h = 198)
h2r<-as.data.frame(locator(n=10, type="l"))
h2rDate<-as.Date(h2r$x)
h2r<-cbind(h2r, h2rDate)
locator(n=10, type="l")

##Status
hm <- hcv(iraq$date, iraq$Status, display="none")
sm.regression(y = iraq$Status, x = iraq$date, h = 58)
s<-as.data.frame(locator(n=40, type="l"))
sDate<-as.Date(s$x)
s<-cbind(s,sDate)
sm.regression(y = iraq$Status, x = iraq$date, h = 58, col.points="white")
sm.regression(y = iraq$Status, x = iraqmat, h = 58)
sm.regression(y = iraqD$Status, x = iraqD$date, h = 58)
sd<-as.data.frame(locator(n=40, type="l"))
sdDate<-as.Date(sd$x)
sd<-cbind(sd,sdDate)
sm.regression(y = iraqR$Status, x = iraqR$date, h = 58)
sr<-as.data.frame(locator(n=40, type="l"))
srDate<-as.Date(sr$x)
sr<-cbind(sr,srDate)

hm <- hcv(ink$date, ink$Status, display="none")
sm.regression(y = ink$Status, x = ink$date, h = 74)
s2<-as.data.frame(locator(n=40, type="l"))
s2Date<-as.Date(s2$x)
s2<-cbind(s2,s2Date)
sm.regression(ink$Status~ink$date, h = 74, col.points="white")
sm.regression(y = ink$Status, x = inkmat, h = 74)
sm.regression(y = inkD$Status, x = inkD$date, h = 74)
sd2<-as.data.frame(locator(n=40, type="l"))
sd2Date<-as.Date(sd2$x)
sd2<-cbind(sd2,sd2Date)
sm.regression(y = inkR$Status, x = inkR$date, h = 74)
sr2<-as.data.frame(locator(n=40, type="l"))
sr2Date<-as.Date(sr2$x)
sr2<-cbind(sr2,sr2Date)
locator(n=10, type="l")


##Categorical Thinking
hm <- hcv(iraq$date, iraq$CatThink, display="none")
sm.regression(y = iraq$CatThink, x = iraq$date, h = 136)
cat=as.data.frame(locator(n=40, type="l"))
catDate=as.Date(cat$x)
cat=cbind(cat,catDate)
sm.regression(y = iraq$CatThink, x = iraq$date, h = 136, col.points="white")
sm.regression(y = iraq$CatThink, x = iraqmat, h = 136)
sm.regression(y = iraqD$CatThink, x = iraqD$date, h = 136)
catd=as.data.frame(locator(n=40, type="l"))
catdDate=as.Date(catd$x)
catd=cbind(catd,catdDate)
sm.regression(y = iraqR$CatThink, x = iraqR$date, h = 136)
catr=as.data.frame(locator(n=40, type="l"))
catrDate=as.Date(catr$x)
catr=cbind(catr,catrDate)
locator(n=10, type="l")

hm <- hcv(ink$date, ink$CatThink, display="none")
sm.regression(y = ink$CatThink, x = ink$date, h = 103)
cat2=as.data.frame(locator(n=40, type="l"))
cat2Date=as.Date(cat2$x)
cat2=cbind(cat2,cat2Date)
sm.regression(y = ink$CatThink, x = ink$date, h = 103, col.points="white")
sm.regression(y = ink$CatThink, x = inkmat, h = 103)
sm.regression(y = inkD$CatThink, x = inkD$date, h = 103)
cat2d=as.data.frame(locator(n=40, type="l"))
cat2dDate=as.Date(cat2d$x)
cat2d=cbind(cat2d,cat2dDate)
sm.regression(y = inkR$CatThink, x = inkR$date, h = 103)
cat2r=as.data.frame(locator(n=40, type="l"))
cat2rDate=as.Date(cat2r$x)
cat2r=cbind(cat2r,cat2rDate)
locator(n=10, type="l")

##Complex Thinking
hm <- hcv(iraq$date, iraq$ComplexThink, display="none")
sm.regression(y = iraq$ComplexThink, x = iraq$date, h = 56)
com=as.data.frame(locator(n=40, type="l"))
comDate=as.Date(com$x)
com=cbind(com, comDate)
sm.regression(y = iraq$ComplexThink, x = iraq$date, h = 56, col.points="white")
sm.regression(y = iraq$ComplexThink, x = iraqmat, h = 56)
sm.regression(y = iraqD$ComplexThink, x = iraqD$date, h = 56)
comd=as.data.frame(locator(n=40, type="l"))
comdDate=as.Date(comd$x)
comd=cbind(comd, comdDate)
sm.regression(y = iraqR$ComplexThink, x = iraqR$date, h = 56)
comr=as.data.frame(locator(n=50, type="l"))
comrDate=as.Date(comr$x)
comr=cbind(comr, comrDate)
locator(n=10, type="l")

hm <- hcv(ink$date, ink$ComplexThink, display="none")
sm.regression(y = ink$ComplexThink, x = ink$date, h = 124)
com2=as.data.frame(locator(n=40, type="l"))
com2Date=as.Date(com2$x)
com2=cbind(com2, com2Date)
sm.regression(y = ink$ComplexThink, x = ink$date, h = 124, col.points="white")
sm.regression(y = ink$ComplexThink, x = inkmat, h = 124)
sm.regression(y = inkD$ComplexThink, x = inkD$date, h = 124)
com2d=as.data.frame(locator(n=40, type="l"))
com2dDate=as.Date(com2d$x)
com2d=cbind(com2d, com2dDate)
sm.regression(y = inkR$ComplexThink, x = inkR$date, h = 124)
com2r=as.data.frame(locator(n=40, type="l"))
com2rDate=as.Date(com2r$x)
com2r=cbind(com2r, com2rDate)
locator(n=10, type="l")

##Cognitive Processing
hm <- hcv(iraq$date, iraq$CogProcess, display="none")
sm.regression(y = iraq$CogProcess, x = iraq$date, h = 34)
cp=as.data.frame(locator(n=50, type="l"))
cpDate=as.Date(cp$x)
cp=cbind(cp, cpDate)
sm.regression(y = iraq$CogProcess, x = iraq$date, h = 34, col.points="white")
sm.regression(y = iraq$CogProcess, x = iraqmat, h = 34)
sm.regression(y = iraqD$CogProcess, x = iraqD$date, h = 34)
cpd=as.data.frame(locator(n=50, type="l"))
cpdDate=as.Date(cpd$x)
cpd=cbind(cpd, cpdDate)
sm.regression(y = iraqR$CogProcess, x = iraqR$date, h = 34)
cpr=as.data.frame(locator(n=50, type="l"))
cprDate=as.Date(cpr$x)
cpr=cbind(cpr, cprDate)
locator(n=10, type="l")

hm <- hcv(ink$date, ink$CogProcess, display="none")
sm.regression(y = ink$CogProcess, x = ink$date, h = 210)
cp2=as.data.frame(locator(n=50, type="l"))
cp2Date=as.Date(cp2$x)
cp2=cbind(cp2, cp2Date)
sm.regression(y = ink$CogProcess, x = ink$date, h = 210, col.points="white")
sm.regression(y = ink$CogProcess, x = inkmat, h = 210)
sm.regression(y = inkD$CogProcess, x = inkD$date, h = 210)
cp2d=as.data.frame(locator(n=50, type="l"))
cp2dDate=as.Date(cp2d$x)
cp2d=cbind(cp2d, cp2dDate)
sm.regression(y = inkR$CogProcess, x = inkR$date, h = 210)
cp2r=as.data.frame(locator(n=50, type="l"))
cp2rDate=as.Date(cp2r$x)
cp2r=cbind(cp2r, cp2rDate)
locator(n=10, type="l")

##Psychological Distancing
hm <- hcv(iraq$date, iraq$PsychDistance, display="none")
sm.regression(y = iraq$PsychDistance, x = iraq$date, h = 145)
pd=as.data.frame(locator(n=50, type="l"))
pdDate=as.Date(pd$x)
pd=cbind(pd, pdDate)
sm.regression(y = iraq$PsychDistance, x = iraq$date, h = 145, col.points="white")
sm.regression(y = iraq$PsychDistance, x = iraqmat, h = 145)
sm.regression(y = iraqD$PsychDistance, x = iraqD$date, h = 145)
pdd=as.data.frame(locator(n=50, type="l"))
pddDate=as.Date(pdd$x)
pdd=cbind(pdd, pddDate)
sm.regression(y = iraqR$PsychDistance, x = iraqR$date, h = 145)
pdr=as.data.frame(locator(n=50, type="l"))
pdrDate=as.Date(pdr$x)
pdr=cbind(pdr, pdrDate)
locator(n=10, type="l")

hm <- hcv(ink$date, ink$PsychDistance, display="none")
sm.regression(y = ink$PsychDistance, x = ink$date, h = 81)
pd2=as.data.frame(locator(n=50, type="l"))
pd2Date=as.Date(pd2$x)
pd2=cbind(pd2, pd2Date)
sm.regression(y = ink$PsychDistance, x = ink$date, h = 81, col.points="white")
sm.regression(y = ink$PsychDistance, x = inkmat, h = 81)
sm.regression(y = inkD$PsychDistance, x = inkD$date, h = 81)
pd2d=as.data.frame(locator(n=50, type="l"))
pd2dDate=as.Date(pd2d$x)
pd2d=cbind(pd2d, pd2dDate)
sm.regression(y = inkR$PsychDistance, x = inkR$date, h = 81)
pd2r=as.data.frame(locator(n=50, type="l"))
pd2rDate=as.Date(pd2r$x)
pd2r=cbind(pd2r, pd2rDate)
locator(n=10, type="l")







sm.regression(y = iraqD$CogProcess, x = iraqD$date, h = 50, col.points="white")
sm.regression(y = iraqR$CogProcess, x = iraqR$date, h = 50, col.points="white")
locator(n=10, type="l")







sm.regression(y = iraqD$ComplexThink, x = iraqD$date, h = 50, col.points="white")
sm.regression(y = iraqR$ComplexThink, x = iraqR$date, h = 50, col.points="white")
identify(y = iraq$ComplexThink, x = iraq$date, n = 10, plot=TRUE)
locator(n=10, type="l")
plot(ComplexThink~date, iraq, main="Complex Thinking", pch=".")
lines(ksmooth(iraq$date, iraq$ComplexThink, "normal", 1))
hm <- hcv(iraq$date, iraq$ComplexThink, display="lines")
sm.regression(y=iraq$ComplexThink, iraq$date, h=hm, xlab="x", ylab="y")
identify(y = iraq$ComplexThink, x = iraq$date, n = 10, plot=TRUE)



####Graphs
ax=c("2-13-00", "11-9-02", "8-5-05", "5-1-08","1-26-11","10-22-13")
bx=c(11000, 12000, 13000, 14000, 15000, 16000)

par(xaxt="n")
sm.regression(y = iraqD$Honesty, x = iraqD$date, h = 185, lty=1, col.points="grey", xlab="Date", ylab="Honesty", axis(side=1, labels=ax, at=bx, las=2))
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$Honesty, x = iraqR$date, h = 185, add=T, lty=3)
legend('bottomleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
h<-as.data.frame(locator(n=50, type="l"))
hDate<-as.Date(h$x)
h<-cbind(h, hDate)

par(xaxt="n")
sm.regression(y = inkD$Honesty, x = inkD$date, h = 198, lty=1, col.points="grey", xlab="Date", ylab="Honesty", axis(side=1, labels=ax, at=bx, las=2))
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$Honesty, x = inkR$date, h = 198, add=T, lty=3)
legend('topleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
h2<-as.data.frame(locator(n=50, type="l"))
h2Date<-as.Date(h2$x)
h2<-cbind(h2, h2Date)

par(xaxt="n")
sm.regression(y = iraqD$Status, x = iraqD$date, h = 58, lty=1, col.points="grey", xlab="Date", ylab="Status")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$Status, x = iraqR$date, h = 58, add=T, lty=3)
legend('topleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
s<-as.data.frame(locator(n=40, type="l"))
sDate<-as.Date(s$x)
s<-cbind(s,sDate)

par(xaxt="n")
sm.regression(y = inkD$Status, x = inkD$date, h = 74, lty=1, col.points="grey", xlab="Date", ylab="Status")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$Status, x = inkR$date, h = 74, add=T, lty=3)
legend('bottomleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
s2<-as.data.frame(locator(n=40, type="l"))
s2Date<-as.Date(s2$x)
s2<-cbind(s2,s2Date)

par(xaxt="n")
sm.regression(y = iraqD$CatThink, x = iraqD$date, h = 136, lty=1, col.points="grey", xlab="Date", ylab="Categorical Thinking")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$CatThink, x = iraqR$date, h = 136, add=T, lty=3)
legend('topleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
cat=as.data.frame(locator(n=40, type="l"))
catDate=as.Date(cat$x)
cat=cbind(cat,catDate)

par(xaxt="n")
sm.regression(y = inkD$CatThink, x = inkD$date, h = 103, lty=1, col.points="grey", xlab="Date", ylab="Categorical Thinking")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$CatThink, x = inkR$date, h = 103, add=T, lty=3)
legend('bottomleft', legend=c("Democrat", "Republican") , lty=c(1, 3), bty='n', cex=.75)
cat2=as.data.frame(locator(n=40, type="l"))
cat2Date=as.Date(cat2$x)
cat2=cbind(cat2,cat2Date)


par(xaxt="n")
sm.regression(y = iraq$ComplexThink, x = iraq$date, h = 56, lty=1, col.points="grey", xlab="Date", ylab="Complex Thinking")
par(xaxt="s")
sm.regression(y = iraqD$ComplexThink, x = iraqD$date, h = 56, lty=3, add=T, col.points="grey", xlab="Date", ylab="Complex Thinking")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$ComplexThink, x = iraqR$date, h = 56, add=T, lty=5)
legend('topleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
com=as.data.frame(locator(n=40, type="l"))
comDate=as.Date(com$x)
com=cbind(com, comDate)


par(xaxt="n")
sm.regression(y = ink$ComplexThink, x = ink$date, h = 124, lty=1, col.points="grey", xlab="Date", ylab="Complex Thinking")
sm.regression(y = inkD$ComplexThink, x = inkD$date, h = 124, add=T, lty=3, col.points="grey", xlab="Date", ylab="Complex Thinking")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$ComplexThink, x = inkR$date, h = 124, add=T, lty=5)
legend('bottomleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
com2=as.data.frame(locator(n=40, type="l"))
com2Date=as.Date(com2$x)
com2=cbind(com2, com2Date)

par(xaxt="n")
sm.regression(y = iraq$CogProcess, x = iraq$date, h = 34, lty=1, col.points="grey", xlab="Date", ylab="Cognitive Processing")
par(xaxt="s")
sm.regression(y = iraqD$CogProcess, x = iraqD$date, h = 34, lty=3, add=T, col.points="grey", xlab="Date", ylab="Cognitive Processing")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$CogProcess, x = iraqR$date, h = 34, add=T, lty=5)
legend('topleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
cp=as.data.frame(locator(n=50, type="l"))
cpDate=as.Date(cp$x)
cp=cbind(cp, cpDate)


par(xaxt="n")
sm.regression(y = ink$CogProcess, x = ink$date, h = 210, lty=1, col.points="grey", xlab="Date", ylab="Cognitive Processing")
sm.regression(y = inkD$CogProcess, x = inkD$date, h = 210, add=T, lty=3, col.points="grey", xlab="Date", ylab="Cognitive Processing")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$CogProcess, x = inkR$date, h = 210, add=T, lty=5)
legend('bottomleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
cp2=as.data.frame(locator(n=50, type="l"))
cp2Date=as.Date(cp2$x)
cp2=cbind(cp2, cp2Date)


par(xaxt="n")
sm.regression(y = iraq$PsychDistance, x = iraq$date, h = 145, lty=1, col.points="grey", xlab="Date", ylab="Psychological Distancing")
par(xaxt="s")
sm.regression(y = iraqD$PsychDistance, x = iraqD$date, h = 145, lty=3, add=T, col.points="grey", xlab="Date", ylab="Psychological Distancing")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = iraqR$PsychDistance, x = iraqR$date, h = 145, add=T, lty=5)
legend('bottomleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
pd=as.data.frame(locator(n=50, type="l"))
pdDate=as.Date(pd$x)
pd=cbind(pd, pdDate)


par(xaxt="n")
sm.regression(y = ink$PsychDistance, x = ink$date, h = 81, lty=1, col.points="grey", xlab="Date", ylab="Psychological Distancing")
sm.regression(y = inkD$PsychDistance, x = inkD$date, h = 81, add=T, lty=3, col.points="grey", xlab="Date", ylab="Psychological Distancing")
par(xaxt="s")
axis(side=1, labels=ax, at=bx, las=1)
sm.regression(y = inkR$PsychDistance, x = inkR$date, h = 81, add=T, lty=5)
legend('bottomleft', legend=c("Overall","Democrat", "Republican") , lty=c(1, 3, 5), bty='n', cex=.75)
pd2=as.data.frame(locator(n=50, type="l"))
pd2Date=as.Date(pd2$x)
pd2=cbind(pd2, pd2Date)
