library(lme4)
library(Matrix);library(lattice)
setwd("C:/Users/Kayla/Dropbox/Kayla war ling analysis/SWPA")
IKData<-as.data.set(spss.system.file("C:/Users/Kayla/Dropbox/Kayla war ling analysis/SWPA/Predictors Only Senate Language Data ONLY Iraq and Kosovo.sav"), use.value.labels=TRUE, to.data.frame=TRUE)
M1<-glmer(OpposeSupport~WPS+Sixltr+Dic+(1|Name)+(1|Regions), data=IKData, family=binomial, na.action=na.omit)
summary(M1)
M2<-glmer(OpposeSupport~i+we+you+shehe+they+(1|Name)+(1|Regions), data=IKData, family=binomial, na.action=na.omit)
summary(M2)
M3<-glmer(OpposeSupport~auxverb+past+present+future+(1|Name)+(1|Regions), data=IKData, family=binomial, na.action=na.omit)
summary(M3)
M4<-glmer(OpposeSupport~article+adverb+preps+conj+negate+quant+(1|Name)+(1|Regions), data=ikData, family=binomial, na.action=na.omit)
summary(M4)
M5<-glmer(OpposeSupport~social+posemo+negemo+(1|Name)+(1|Regions), data=IKData, family=binomial, na.action=na.omit)
summary(M5)
M6<-glmer(OpposeSupport~insight+cause+discrep+tentat+certain+inhib+incl+excl+(1|Name)+(1|Regions), data=ikData, family=binomial, na.action=na.omit)
summary(M6)
M7<-glmer(OpposeSupport~motion+space+time+(1|Name)+(1|Regions), data=ikData, family=binomial, na.action=na.omit)
summary(M7)
M8<-glmer(OpposeSupport~work+achieve+money+relig+death+(1|Name)+(1|Regions), data=ikData, family=binomial, na.action=na.omit)
summary(M8)
M9<-glmer(OpposeSupport~WPS+Sixltr+Dic+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M9)
M10<-glmer(OpposeSupport~i+we+you+shehe+they+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M10)
M11<-glmer(OpposeSupport~auxverb+past+present+future+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M11)
M12<-glmer(OpposeSupport~article+adverb+preps+conj+negate+quant+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M12)
M13<-glmer(OpposeSupport~social+posemo+negemo+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M13)
M14<-glmer(OpposeSupport~insight+cause+discrep+tentat+certain+inhib+incl+excl+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M14)
M15<-glmer(OpposeSupport~motion+space+time+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M15)
M16<-glmer(OpposeSupport~work+achieve+money+relig+death+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M16)
M17<-glmer(OpposeSupport~WPS+Sixltr+Dic+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M17)
M18<-glmer(OpposeSupport~i+we+you+shehe+they+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M18)
M19<-glmer(OpposeSupport~auxverb+past+present+future+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M19)
M20<-glmer(OpposeSupport~article+adverb+preps+conj+negate+quant+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M20)
M21<-glmer(OpposeSupport~social+posemo+negemo+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M21)
M22<-glmer(OpposeSupport~insight+cause+discrep+tentat+certain+inhib+incl+excl+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M22)
M23<-glmer(OpposeSupport~motion+space+time+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M23)
M24<-glmer(OpposeSupport~work+achieve+money+relig+death+(1|Name)+(1|PartyAffliation), data=ikData, family=binomial, na.action=na.omit)
summary(M24)
anova(M1,M2,M3,M4,M5,M6,M7,M8,M9,M10,M11,M12,M13,M14,M15,M16,M17,M18,M19,M20,M21,M22,M23,M24)
anova(M1,M7)
anova(M7,M5)
anova(M5,M3)