library(lme4)
library(Matrix);library(lattice)
setwd("C:/Users/Kayla/Dropbox/Kayla war ling analysis/SWPA")
ikData2<-as.data.set(spss.system.file("R Iraq and Kosovo More Predictors.sav"), use.value.labels=TRUE, to.data.frame=TRUE)
ikData=read.csv("R Iraq and Kosovo More Predictors.csv", header=TRUE)

M1<-glmer(OpposeSupport~WPS+Sixltr+Dic+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M1)
M2<-glmer(OpposeSupport~i+we+you+shehe+they+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M2)
M3<-glmer(OpposeSupport~auxverb+past+present+future+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M3)
M4<-glmer(OpposeSupport~article+adverb+preps+conj+negate+quant+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M4)
M5<-glmer(OpposeSupport~social+posemo+negemo+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M5)
M6<-glmer(OpposeSupport~insight+cause+discrep+tentat+certain+inhib+incl+excl+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M6)
M7<-glmer(OpposeSupport~motion+space+time+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M7)
M8<-glmer(OpposeSupport~work+achieve+money+relig+death+(1|Name), data=ikData, family=binomial, na.action=na.omit)
summary(M8)
anova(M1,M2,M3,M4,M5,M6,M7,M8)